
resources: 
- deployment.yaml
- service.yaml
- pod.yaml

commonLabels:
  app: moja

commonAnnotations:
  app: mykustom-annontations

namePrefix:
  kustom-

nameSuffix:
  -v2

configMapGenerator:
- name: mykustom-map
  env: config.properties
