
resources: 
- deployment.yaml
- service.yaml
- pod.yaml

commonLabels:
  app: twoja

commonAnnotations:
  app: mykustom-annontations

namePrefix:
  kustom-apka

nameSuffix:
  -v2

configMapGenerator:
- name: mykustom-map
  env: config.properties
